export const BASKET = "BASKET";
export const BASKET_ADD_ITEM = "BASKET_ADD_ITEM";
export const BASKET_REMOVE_ITEM = "BASKET_REMOVE_ITEM";
export const BASKET_ADD_AMOUNT = "BASKET_ADD_AMOUNT";
export const BASKET_SUB_AMOUNT = "BASKET_SUB_AMOUNT";